xml: Use OpenSBI instead of BBL
seL4/sel4test-manifest pull request #7
Opened 2020-10-23 22:31 UTC by alistair23

Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

2020-10-23 22:49 UTC, yyshen commented
Hi @alistair23 Thanks for the contribution! OpenSBI has support for the most recent hypervisor extension, right?

2020-10-23 22:50 UTC, alistair23 commented
Yes, it does

2020-10-24 04:31 UTC, yyshen commented
@LukeMondy Can bamboo test the manifest changes?

2020-10-25 23:09 UTC, LukeMondy commented
:thinking: it should, or at the very least, setup the PR so we can run the test.

2020-10-28 04:14 UTC, szhuang requested changes
Thanks for contributing code.

2020-10-28 04:14 UTC, szhuang commented on common.xml
> +<remote fetch="https://github.com/riscv/opensbi" name="opensbi"/>
"remote" should be the account URL.
```suggestion
<remote fetch="https://github.com/riscv" name="opensbi"/>
```

2020-10-28 04:14 UTC, szhuang commented on default.xml
> +  <remote fetch="https://github.com/riscv/opensbi" name="opensbi"/>
```suggestion
  <remote fetch="https://github.com/riscv" name="opensbi"/>
```

2020-11-05 21:33 UTC, alistair23 commented
I have addressed your comments.

2020-12-16 12:47 UTC, axel-h commented
Looks fine to me - unless somebody has a reason to keep sel4proj/riscv-pk around for some legacy compatibility. But dropping it might be a good motivation to cut the legacy.

2020-12-16 12:54 UTC, axel-h approved these changes

2021-01-05 19:26 UTC, alistair23 commented
Ping!

2021-01-20 17:19 UTC, alistair23 commented
Ping!

2021-03-08 23:53 UTC, oliver-wm commented
@ssrg-bamboo `test`

2021-03-08 23:54 UTC, ssrg-bamboo commented
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

2021-03-08 23:55 UTC, ssrg-bamboo commented
All the tests we ran have passed! Nice job!

2021-03-09 00:33 UTC, ssrg-bamboo commented
All the tests we ran have passed! Nice job!

2021-03-16 02:29 UTC, closed without merging

2021-03-16 13:49 UTC, alistair23 commented
It doesn't seem like this has been merged

2021-03-16 21:51 UTC, lsf37 commented
(same as on seL4/sel4test#28)

It's been merged internally and will be pushed out to on GitHub as soon as CI passes (there are some networking problems which makes that process slow at them moment, because it leads to intermittent hardware test failures).